/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.kmptemplate.app

object MessageUtils {
    private const val message = "Hello      World!"
    fun getMessage(): String = message
}

