/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.kmptemplate.utilities

import io.kmptemplate.list.LinkedList

object JoinUtils {
    fun join(source: LinkedList): String {
        val result = StringBuilder()
        for (i in 0 until source.size()) {
            if (result.isNotEmpty()) {
                result.append(" ")
            }
            result.append(source.get(i))
        }

        return result.toString()
    }
}
