/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.kmptemplate.utilities

import io.kmptemplate.list.LinkedList

object StringUtils {
    fun join(source: LinkedList): String {
        return JoinUtils.join(source)
    }

    fun split(source: String): LinkedList {
        return SplitUtils.split(source)
    }
}
